# site settings
title: FST Blog
SEOTitle: fst的博客 | FST Blog
header-img: img/post-bg-rwd.jpg   #显示在首页的背景图片
email: fst@gmail.com
description: "FST Blog"        #网站介绍
keyword: "fst, FST Blog, fst的博客" #关键词


# URL settings
url: "https://stfeng.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'


# Markdown settings
markdown: kramdown


# SNS settings
github_username: stfeng


# Analytics settins
# Baidu 

# Google


permalink: blog/:year/:month/:day/:title 



